# Generated by Django 4.2.2 on 2023-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name_1", models.CharField(max_length=200)),
                ("last_name_1", models.CharField(max_length=200)),
                ("email_1", models.EmailField(max_length=200)),
            ],
        ),
    ]
