# Generated by Django 4.2.2 on 2023-07-20 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="Person_model",
        ),
    ]
