# Generated by Django 4.2.2 on 2023-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triangle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.CharField(max_length=200)),
                ("path", models.CharField(max_length=200)),
                ("method", models.CharField(max_length=200)),
                ("query", models.CharField(max_length=200)),
                ("body", models.CharField(max_length=200)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
